language: php

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
    include:
        - php: 7.1
        - php: 7.2
        - php: 7.1
          env: deps=low
        - php: nightly
